import Head from "next/head";
import Link from "next/link";
import { Layout } from "@/components/layout/Layout";

const LAST_UPDATED = "April 23, 2026";

export default function PrivacyPage() {
  return (
    <Layout>
      <Head>
        <title>Privacy Policy — funded.gr</title>
        <meta
          name="description"
          content="Privacy Policy for funded.gr — how we collect and use your data."
        />
      </Head>

      <div className="max-w-3xl">
        <div className="mb-10">
          <p className="text-xs font-mono text-gray-400 mb-2">
            Last updated: {LAST_UPDATED}
          </p>
          <h1 className="text-3xl font-bold tracking-tight text-gray-900 mb-2">
            Privacy Policy
          </h1>
          <p className="text-gray-500 text-sm">
            This policy explains what personal data funded.gr collects, why we
            collect it, and your rights under the General Data Protection
            Regulation (GDPR).
          </p>
        </div>

        <div className="space-y-8">
          <Section title="1. Data Controller">
            <p>
              The data controller for funded.gr is the platform operator,
              reachable at{" "}
              <a
                href="mailto:info@funded.gr"
                className="text-blue-600 hover:underline font-mono"
              >
                info@funded.gr
              </a>
              . All data is processed in accordance with Regulation (EU)
              2016/679 (GDPR).
            </p>
          </Section>

          <Section title="2. Data We Collect">
            <p>We collect the following categories of personal data:</p>
            <table>
              <thead>
                <tr>
                  <th>Category</th>
                  <th>Data</th>
                  <th>Source</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Account</td>
                  <td>Email address, display name</td>
                  <td>Provided by you at registration</td>
                </tr>
                <tr>
                  <td>Project</td>
                  <td>Project name, description, URLs, contact email</td>
                  <td>Provided by you when submitting a project</td>
                </tr>
                <tr>
                  <td>Usage</td>
                  <td>Likes, evaluation requests</td>
                  <td>Generated by your interactions with the platform</td>
                </tr>
                <tr>
                  <td>Contact</td>
                  <td>Name, email, message content</td>
                  <td>Provided by you when using the contact form</td>
                </tr>
              </tbody>
            </table>
            <p>
              We do not collect payment information, precise location data, or
              any special categories of personal data as defined in Article 9
              GDPR.
            </p>
          </Section>

          <Section title="3. Legal Basis for Processing">
            <p>We process your personal data on the following legal bases:</p>
            <ul>
              <li>
                <strong>Contract (Art. 6(1)(b)):</strong> to provide the
                services you registered for, including account management and
                project publishing.
              </li>
              <li>
                <strong>Legitimate interests (Art. 6(1)(f)):</strong> to
                maintain the security and integrity of the platform, and to
                improve our services.
              </li>
              <li>
                <strong>Consent (Art. 6(1)(a)):</strong> where you have
                explicitly provided consent, such as when submitting a contact
                form message.
              </li>
            </ul>
          </Section>

          <Section title="4. How We Use Your Data">
            <ul>
              <li>To create and manage your account</li>
              <li>To publish and display your submitted project</li>
              <li>
                To generate AI-assisted project evaluations based on your
                project content
              </li>
              <li>To respond to contact form submissions</li>
              <li>
                To detect and prevent abuse, spam, and fraudulent activity
              </li>
              <li>To communicate important service updates</li>
            </ul>
            <p>
              We do not use your data for automated decision-making that
              produces legal or similarly significant effects, except as part of
              the optional AI evaluation which you must explicitly request.
            </p>
          </Section>

          <Section title="5. Data Storage &amp; Transfers">
            <p>
              Your data is stored on cloud infrastructure located within the
              European Union. No personal data is transferred to countries
              outside the EEA without adequate safeguards in place.
            </p>
          </Section>

          <Section title="6. Data Sharing">
            <p>
              We do not sell, rent, or trade your personal data. We may share
              data with:
            </p>
            <ul>
              <li>
                <strong>Cloud infrastructure providers</strong> — for hosting,
                authentication, and data storage services
              </li>
              <li>
                <strong>AI processing services</strong> — solely to generate
                project evaluations; only project content is submitted, not
                account data
              </li>
              <li>
                <strong>Bot protection services</strong> — to verify that
                contact form submissions are made by humans
              </li>
              <li>
                <strong>Law enforcement</strong> — if required by applicable law
                or a valid legal order
              </li>
            </ul>
          </Section>

          <Section title="7. Data Retention">
            <p>
              We retain account and project data for as long as your account is
              active. Contact form messages are retained for 12 months, after
              which they are permanently deleted.
            </p>
            <p>
              When you delete your account, we delete or anonymise your personal
              data within 30 days, except where retention is required by law.
            </p>
          </Section>

          <Section title="8. Your Rights">
            <p>Under GDPR, you have the following rights:</p>
            <ul>
              <li>
                <strong>Access (Art. 15):</strong> request a copy of the data we
                hold about you
              </li>
              <li>
                <strong>Rectification (Art. 16):</strong> correct inaccurate or
                incomplete data
              </li>
              <li>
                <strong>Erasure (Art. 17):</strong> request deletion of your
                personal data. Note that if you have requested an AI evaluation,
                your project data is locked for up to 30 days from the
                evaluation date — deletion of that data will be fulfilled once
                the lock period expires.
              </li>
              <li>
                <strong>Restriction (Art. 18):</strong> restrict processing in
                certain circumstances
              </li>
              <li>
                <strong>Portability (Art. 20):</strong> receive your data in a
                machine-readable format
              </li>
              <li>
                <strong>Objection (Art. 21):</strong> object to processing based
                on legitimate interests
              </li>
              <li>
                <strong>Withdraw consent:</strong> where processing is based on
                consent, you may withdraw it at any time without affecting the
                lawfulness of prior processing
              </li>
            </ul>
            <p>
              To exercise any of these rights, please{" "}
              <Link href="/contact" className="text-blue-600 hover:underline">
                contact us
              </Link>
              . We will respond within 30 days. You also have the right to lodge
              a complaint with the Hellenic Data Protection Authority (HDPA) at{" "}
              <a
                href="https://www.dpa.gr"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 hover:underline font-mono"
              >
                www.dpa.gr
              </a>
              .
            </p>
          </Section>

          <Section title="9. Cookies &amp; Local Storage">
            <p>
              funded.gr uses browser localStorage to store your authentication
              session tokens. No third-party advertising or tracking cookies are
              used. A bot protection service may set a cookie on the contact
              page only, solely to distinguish human visitors from automated
              traffic.
            </p>
          </Section>

          <Section title="10. Changes to This Policy">
            <p>
              We may update this Privacy Policy periodically. Material changes
              will be communicated via the platform. The "Last updated" date at
              the top of this page always reflects the most recent revision.
            </p>
          </Section>

          <Section title="11. Contact &amp; Data Requests">
            <p>
              For any privacy-related enquiries or to exercise your rights,
              please{" "}
              <Link href="/contact" className="text-blue-600 hover:underline">
                contact us
              </Link>{" "}
              or email{" "}
              <a
                href="mailto:info@funded.gr"
                className="text-blue-600 hover:underline font-mono"
              >
                info@funded.gr
              </a>
              .
            </p>
          </Section>
        </div>
      </div>
    </Layout>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="text-base font-semibold text-gray-900 mb-3">{title}</h2>
      <div className="space-y-3 text-sm text-gray-600 leading-relaxed [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_table]:w-full [&_table]:border-collapse [&_th]:text-left [&_th]:text-xs [&_th]:font-semibold [&_th]:text-gray-500 [&_th]:uppercase [&_th]:tracking-wide [&_th]:pb-2 [&_td]:py-2 [&_td]:pr-4 [&_td]:align-top [&_tr]:border-t [&_tr]:border-gray-100 [&_strong]:font-semibold [&_strong]:text-gray-700">
        {children}
      </div>
    </section>
  );
}
